### ISSUE TITLE
New version does not work with python 3

### ISSUE THREAD

**Issue by Serranya** [gapato/livestreamer-curses#13]
The new Release breaks support for python 3.

If i try to build livestreamer-curses from source i get

    Traceback (most recent call last):
      File "setup.py", line 10, in <module>
        from livestreamer_curses import config
      File "/home/serra/pkgs/arch_linux/AUR/livestreamer-curses/src/livestreamer-curses-1.5.0/src/livestreamer_curses/__init__.py", line 1, in <module>
        from config import VERSION as __version__
    ImportError: No module named 'config'

I can however build it with python2.

If i try to start the program with python3 i get

    Traceback (most recent call last):
      File "/usr/bin/livestreamer-curses", line 5, in <module>
        from pkg_resources import load_entry_point
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3020, in <module>
        working_set = WorkingSet._build_master()
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
        ws.require(__requires__)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 920, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 807, in resolve
        raise DistributionNotFound(req)
    pkg_resources.DistributionNotFound: livestreamer

EDIT:
If you dont want to keep compability with python3, maybe use

    #!/usr/bin/python2

as your shebang.

**Comment by gapato** [comment]
My bad, I don't test python3 systematically. Quick fix coming your way.

**Comment by Serranya** [comment]
I can compile the Program now. However when trying to start it i get:

    Traceback (most recent call last):
      File "/usr/bin/livestreamer-curses", line 9, in <module>
        load_entry_point('livestreamer-curses==1.5.1', 'console_scripts', 'livestreamer-curses')()
      File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 521, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2632, in load_entry_point
        return ep.load()
      File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2312, in load
        return self.resolve()
      File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2318, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/usr/lib/python3.4/site-packages/livestreamer_curses/main.py", line 34, in <module>
        from .streamlist import StreamList
      File "/usr/lib/python3.4/site-packages/livestreamer_curses/streamlist.py", line 16, in <module>
        from IPython import embed
    ImportError: No module named 'IPython

**Comment by Serranya** [comment]
Never mind. I was missing the ipython package

**Comment by gapato** [comment]
Nonono, this is a stray import, thanks for reporting it. If you would be kind enough to uninstall IPython and try again with the develop branch, that'd be great.

**Comment by Serranya** [comment]
I unistalled IPython and the latest revision from the develop branch is working

**Comment by gapato** [comment]
Thanks, pushed to PyPI!
