### ISSUE TITLE
livestreamer-curses should have a sane colorscheme or atleast have the option to change them myself

### ISSUE THREAD

**Issue by Hund** [gapato/livestreamer-curses#15]
I really like the program. But the default colorscheme are really weird to say the least. Why not use sane values as the rest of the world? :)

http://i.imgur.com/ZrzLTeM.png

**Comment by gapato** [comment]
Ah, good point. I've added color initialization in aad6e8e9b2325b7a775e4d29f4ae97a1f34601e3. Could check if things go as you expect now?

**Comment by Hund** [comment]
Great! I added the change and compiled the program. But when I try to run it I get this:

```
$ livestreamer-curses
Traceback (most recent call last):
  File "/usr/bin/livestreamer-curses", line 9, in <module>
    load_entry_point('livestreamer-curses==1.5.2', 'console_scripts', 'livestreamer-curses')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/lib/python3.4/site-packages/livestreamer_curses-1.5.2-py3.4.egg/livestreamer_curses/main.py", line 34, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/lib/python3.4/site-packages/livestreamer_curses-1.5.2-py3.4.egg/livestreamer_curses/streamlist.py", line 130, in <module>
  File "/usr/lib/python3.4/site-packages/livestreamer_curses-1.5.2-py3.4.egg/livestreamer_curses/streamlist.py", line 220, in StreamList
_curses.error: must call initscr() first
```

**Comment by gapato** [comment]
Uh, how did you install ? I would recommend something like the following:

```
$ git clone https://github.com/gapato/livestreamer-curses
$ git checkout feature/defaultcolors
$ sudo python setup.py install      # or python3 depending on the defaults/aliases on your system
```

**Comment by Hund** [comment]
Since there were no changes to the code on Github I just made a 'git clone'
and added the code from the link myself.

**Comment by gapato** [comment]
This looks fishy, as the exception is raised on import, which should not happen, since no curses calls are made at that point, and not even in `StreamList.__init__`.

Could you please try using the procedure I gave above ?

**Comment by Hund** [comment]
I did. And the program itself works. But I still get the wrong colors though.

**Comment by gjankowiak** [comment]
Is there any way you could provide a test case then or tell me exactly what behavior you expect? I'm not sure I understood what is going wrong.

**Comment by gapato** [comment]
What's the ouput of `git show --shortstat --oneline` ?
If it's different from the following, you're not installing from the right branch.

```
aad6e8e [feature] use terminal's colors
1 file changed, 5 insertions(+)
```

If it's the same, then I don't understand your problem, please be more specific.

**Comment by Hund** [comment]
It works now. Dunno what I did wrong the last time. Thank your for your time! :)

**Comment by gapato** [comment]
Enjoy!
